//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVANTE")]
        public string LABEL_IN_NAME {
            get {
                return ((string)(this["LABEL_IN_NAME"]));
            }
            set {
                this["LABEL_IN_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCBunseal_ScanPKGID_2")]
        public string LABEL_OUT_NAME {
            get {
                return ((string)(this["LABEL_OUT_NAME"]));
            }
            set {
                this["LABEL_OUT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCBunseal_ScanPKGID_2")]
        public string FOCUS_PROCESS_NAME {
            get {
                return ((string)(this["FOCUS_PROCESS_NAME"]));
            }
            set {
                this["FOCUS_PROCESS_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SELECT_FORMAT_BY_SUPPLIER {
            get {
                return ((bool)(this["SELECT_FORMAT_BY_SUPPLIER"]));
            }
            set {
                this["SELECT_FORMAT_BY_SUPPLIER"] = value;
            }
        }
    }
}
